version: '3.8'

services:
  bot:
    image: ghcr.io/lonix/koolbot:latest
    container_name: koolbot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - koolbot-network

  mongodb:
    image: mongo:latest
    container_name: koolbot-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - koolbot-network

networks:
  koolbot-network:
    driver: bridge

volumes:
  mongodb_data: 