services:
  bot:
    image: ghcr.io/lonix/koolbot:latest
    container_name: koolbot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb
    stop_grace_period: 30s
    stop_signal: SIGTERM


  mongodb:
    image: mongo:latest
    container_name: koolbot-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    stop_grace_period: 30s
    stop_signal: SIGTERM

volumes:
  mongodb_data:
