version: '3.8'

services:
  bot:
    build: .
    container_name: koolbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: sh -c "npm run build && npm run deploy-commands && npm start"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: koolbot-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
