version: '3.8'

services:
  koolbot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: koolbot-dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - koolbot-network
    depends_on:
      - mongodb
    stop_grace_period: 30s
    stop_signal: SIGTERM

  mongodb:
    image: mongo:latest
    container_name: koolbot-mongodb-dev
    restart: unless-stopped
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - "27017:27017"
    stop_grace_period: 30s
    stop_signal: SIGTERM

volumes:
  mongodb_data_dev:

networks:
  koolbot-network:
    driver: bridge 
