version: '3.8'

services:
  bot:
    build: .
    command: sh -c "npm run build && npm start"
    environment:
      - NODE_ENV=development
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
