name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure setting '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code.
        You can get logs with: `docker-compose logs -f bot` or `npm run dev`
      render: shell
      placeholder: |
        Paste your logs here...

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running KoolBot?
      options:
        - Docker Compose (Production)
        - Docker Compose (Development)
        - Local npm (Development)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: KoolBot Version
      description: What version of KoolBot are you running?
      placeholder: "e.g., 0.6.0 or commit hash"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "e.g., 20.11.0"
    validations:
      required: true

  - type: input
    id: discord-version
    attributes:
      label: Discord.js Version
      description: What version of Discord.js is installed?
      placeholder: "e.g., 14.25.1"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      options:
        - Linux
        - macOS
        - Windows (WSL2)
        - Windows (Native)
        - Docker (Linux Container)
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Relevant Configuration
      description: |
        Share relevant configuration (REMOVE SENSITIVE DATA like tokens!)
        Use `/config list` to see your settings
      render: yaml
      placeholder: |
        voicechannels.enabled: true
        voicetracking.enabled: true
        # DO NOT INCLUDE TOKENS OR SENSITIVE DATA

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots
        - Related issues
        - Workarounds you've tried
        - When the issue started

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you've tried these basic troubleshooting steps
      options:
        - label: I have checked the troubleshooting guide
        - label: I have tried restarting the bot
        - label: I have checked that my configuration is valid
        - label: I have checked the bot has necessary Discord permissions
        - label: I am using the latest version or a recent stable version
