name: 📚 Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about what needs to be documented or corrected.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a similar documentation issue already exists.
      options:
        - label: I have searched the existing issues
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README.md
        - CONTRIBUTING.md
        - COMMANDS.md
        - SETTINGS.md
        - TESTING.md
        - TROUBLESHOOTING.md
        - SECURITY.md
        - Code Comments
        - Issue/PR Templates
        - API Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Typo or grammar issue
        - Formatting issue
        - Missing examples
        - Broken links
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: |
        Where is the documentation issue located?
        Provide file name, section, or link
      placeholder: |
        File: COMMANDS.md
        Section: Voice Channel Commands
        Line: 123
        URL: https://github.com/lonix/koolbot/blob/main/README.md#section
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's Wrong?
      description: Describe what's missing, incorrect, or unclear
      placeholder: |
        The documentation doesn't explain...
        This section is confusing because...
        The example is outdated...
        There's a typo in...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What Should Be There?
      description: Describe what the documentation should say or include
      placeholder: |
        It should explain...
        There should be an example showing...
        The correct information is...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: |
        If you have specific wording or examples, provide them here
        Feel free to write the documentation you'd like to see
      placeholder: |
        ## Suggested Text
        
        Here's what I think the documentation should say...
        
        ## Example Code
        ```bash
        # Example commands
        ```

  - type: dropdown
    id: user-type
    attributes:
      label: Who Is Affected?
      description: Who would benefit from this documentation improvement?
      options:
        - New users trying to set up KoolBot
        - Users configuring features
        - Developers contributing to the project
        - Advanced users/admins
        - All users
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the documentation issue
      placeholder: |
        - Why this is important
        - Related documentation
        - Screenshots
        - Your experience level

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to help fix this?
      description: |
        We welcome documentation contributions! They're a great way to get started.
        See CONTRIBUTING.md for guidelines.
      options:
        - label: I would like to submit a PR to fix this documentation

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have checked the latest version of the documentation
        - label: I have searched for existing documentation on this topic
        - label: This issue is about the documentation itself (not a feature request or bug)
