name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize]
  status: {}
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' &&
      (github.event_name == 'pull_request_target' ||
       github.event_name == 'status' ||
       github.event_name == 'check_suite')
    steps:
      - name: Auto-merge Dependabot PR
        run: |
          # Wait a moment for any pending checks to register
          sleep 10
          
          # Enable auto-merge with squash
          gh pr merge --auto --squash "$PR_URL" || echo "Auto-merge failed or already enabled"
        env:
          PR_URL: ${{ github.event.pull_request.html_url || github.event.status.target_url || format('https://github.com/{0}/pull/{1}', github.repository, github.event.number) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Alternative job that handles merging when all checks pass
  merge-on-status:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'status' &&
      github.event.state == 'success'
    steps:
      - name: Get PR number from status
        id: pr
        run: |
          PR_NUMBER=$(echo "${{ github.event.target_url }}" | grep -o '[0-9]\+$')
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
      - name: Merge if all checks pass
        if: steps.pr.outputs.number
        run: |
          gh pr merge --squash ${{ steps.pr.outputs.number }} || echo "Merge failed or already merged"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
