name: Validate Dependabot Workflows

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dependabot-*.yml'
      - '.github/dependabot.yml'

jobs:
  validate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Dependabot config
        run: |
          echo "Checking Dependabot configuration..."
          if [ -f .github/dependabot.yml ]; then
            echo "✅ Dependabot config exists"
            echo "Package ecosystem: $(grep 'package-ecosystem:' .github/dependabot.yml | head -1)"
            echo "Schedule: $(grep 'interval:' .github/dependabot.yml | head -1)"
          else
            echo "❌ Dependabot config missing"
            exit 1
          fi

      - name: Validate auto-approve workflow
        run: |
          echo "Checking auto-approve workflow..."
          if [ -f .github/workflows/dependabot-auto-approve.yml ]; then
            echo "✅ Auto-approve workflow exists"
            grep -q "dependabot\[bot\]" .github/workflows/dependabot-auto-approve.yml && echo "✅ Dependabot actor check found"
            grep -q "pull-requests: write" .github/workflows/dependabot-auto-approve.yml && echo "✅ PR permissions configured"
          else
            echo "❌ Auto-approve workflow missing"
            exit 1
          fi

      - name: Validate auto-merge workflow
        run: |
          echo "Checking auto-merge workflow..."
          if [ -f .github/workflows/dependabot-auto-merge.yml ]; then
            echo "✅ Auto-merge workflow exists"
            grep -q "dependabot\[bot\]" .github/workflows/dependabot-auto-merge.yml && echo "✅ Dependabot actor check found"
            grep -q "contents: write" .github/workflows/dependabot-auto-merge.yml && echo "✅ Contents permissions configured"
          else
            echo "❌ Auto-merge workflow missing"
            exit 1
          fi

      - name: Show current open Dependabot branches
        run: |
          echo "Current Dependabot branches:"
          git branch -r | grep dependabot | head -10 || echo "No Dependabot branches found"

      - name: Summary
        run: |
          echo ""
          echo "🎉 Dependabot automation setup complete!"
          echo ""
          echo "Features configured:"
          echo "- ✅ Weekly dependency checks for npm packages"
          echo "- ✅ Automatic approval of Dependabot PRs"
          echo "- ✅ Automatic merging after tests pass"
          echo "- ✅ Up to 10 concurrent PRs allowed"
          echo ""
          echo "Next steps:"
          echo "1. New Dependabot PRs will be automatically approved"
          echo "2. PRs will auto-merge when all checks pass"
          echo "3. Existing PRs may need manual approval/merge"
